%YAML:1.0
---
###Mono###
IS_MONO: 1

###Control###
FILTER_GROUND: 1
FILTER_BACKGROUND: 1
FILTER_LANE: 1

###Disparity###
#---SGBM---
# DISPARITY_TYPE: 0
# pre_gaussian_kernel: 5
# pre_median_kernel: 5
# max_disparity: 64
# window_size: 3
# prefilter_size: 63
# prefilter_cap: 63
# texture_threshold: 10
# uniqueness_ratio: 10
# wls_lambda: 8000
# wls_sigma: 0.8
#---BM---
DISPARITY_TYPE: 1
pre_gaussian_kernel: 5
pre_median_kernel: 3
max_disparity: 112
window_size: 9 #11
prefilter_size: 31
prefilter_cap: 31
texture_threshold: 10
uniqueness_ratio: 15 #10
speckle_window: 400 #50
speckle_range: 32 #100

###GroundFIlter###
GROUND_FILTER_TYPE: 1
#---Mono---
is_stable: 0
ground_tolerance: 5
#---Online---
ground_tolerance: 10
min_count: 60
max_disparity: 255
min_disparity: 10
hough_min_count: 25
hough_min_length: 100
hough_max_gap: 30

###ObjectFilter###
#---Size---
min_width: 0.1
min_height: 0.1
max_width: 1
max_height: 1
#---NMS---
NMS_threshold: 0.2
#---Confidence---
confidence_threshold: 0.5

###ContourDetector###
DETECTOR_TYPE: 0
#---lane---
#depth_step: 0.1
#num_of_waypoints: 10
#---Detection---
DISPARITY_CALC_TYPE: 0            # 0-median, 1-average, 2-max
median_kernel: 5
canny_threshold: 100





